############################
# Pre-commit configuration #
############################

# Install via `pip install pre-commit`

# This is run as a precondition to commits, run manually via `pre-commit run`

# When adding new hooks, it may make sense to once run
# `pre-commit run --all-files` as by default only changed files are checked

# Automatically run before every commit via once running `pre-commit install`

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # A bunch of other pre-defined hooks.
  - id: check-yaml
    description: Check yaml files for parseable syntax
  - id: check-added-large-files
    description: Prevent large files from being committed
    exclude: ^docs/source/notebooks/
  - id: check-merge-conflict
    description: Check for files that contain merge conflict strings
  - id: detect-private-key
    description: Detects the presence of private keys
-   repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
-   repo: local
    hooks:
    -   id: run-parameters-doc
        name: Run parameters_doc.py
        entry: python docs/source/parameters_doc.py
        language: system
        files: ^docs/source/parameters_doc\.py$
