import os

from usbmd.data_format.usbmd_data_format import generate_example_dataset, validate_dataset


def test_example_dataset():
    """Tests the generate_example_dataset function by calling it and then
    validating it using the validate_dataset function.
    """
    path = 'test_case_dataset.hdf5'

    # Ensure that the file does not exist
    if os.path.exists(path):
        raise FileExistsError(f'The file {path} already exists.')

    # Generate the example dataset
    generate_example_dataset(path)

    try:
        # Validate the dataset
        validate_dataset(path)
    finally:
        # Remove the file generated by this test
        os.remove(path)