"""
Test the pytorch implementation of the beamformers.
"""

import numpy as np

from usbmd.probes import Verasonics_l11_4v
from usbmd.scan import PlaneWaveScan


def test_pfield(debug=False):
    """Performs field computation on a scan object to verify that no errors occur. Does
    not check correctness of the output. Only test with PlaneWaveScan for now.

    Args:
        debug (bool, optional): Set to True to enable debugging options (plotting). Defaults to
        False.
    """

    probe = Verasonics_l11_4v()
    scan = PlaneWaveScan(
        probe_geometry=probe.probe_geometry,
        n_tx=1,
        xlims=(-19e-3, 19e-3),
        zlims=(0, 63e-3),
        n_ax=2047,
        sampling_frequency=probe.sampling_frequency,
        center_frequency=probe.center_frequency,
        angles=np.array([0]),
    )

    scan._focus_distances = np.array([np.inf])

    # Set scan grid parameters
    # The grid is updated automatically when it is accessed after the scan parameters
    # have been changed.
    dx = scan.wvln / 4
    dz = scan.wvln / 4
    scan.Nx = int(np.ceil((scan.xlims[1] - scan.xlims[0]) / dx))
    scan.Nz = int(np.ceil((scan.zlims[1] - scan.zlims[0]) / dz))

    assert scan._pfield is None, "scan._pfield is None when not called yet"

    _ = scan.pfield

    # plot results
    if debug:
        import matplotlib.pyplot as plt  # pylint: disable=import-outside-toplevel

        plt.figure()
        plt.imshow(scan._pfield[0])
        plt.title("Pressure field for Tx1")
        plt.show()

    assert scan._pfield is not None, "scan._pfield must have generated by now"
