"""Test generating and validating usbmd data format.
"""
import os
from pathlib import Path

from usbmd.data_format.usbmd_data_format import (generate_example_dataset,
                                                 validate_dataset)


def test_example_dataset():
    """Tests the generate_example_dataset function by calling it and then
    validating it using the validate_dataset function.
    """
    # Define path to store the example dataset
    path = Path('temp', 'test_case_dataset.hdf5')

    # Create the directory if it does not exist
    path.parent.mkdir(parents=True, exist_ok=True)

    # Generate the example dataset
    generate_example_dataset(path)

    try:
        # Validate the dataset
        validate_dataset(path)
    finally:
        # Remove the file generated by this test
        os.remove(path)
