
init:
  duration: 1
  beamformer: RAW
  na: 11

DAS1PW:
  duration: 60
  beamformer: DAS
  na: 1

DAS5PW:
  duration: 60
  beamformer: DAS
  na: 5

DAS11PW:
  duration: 60
  beamformer: DAS
  na: 11

ABLE1PW:
  duration: 60
  beamformer: ABLE
  na: 1

ABLE5PW:
  duration: 60
  beamformer: ABLE
  na: 5

ABLE11PW:
  duration: 60
  beamformer: ABLE
  na: 11

RAW1PW:
  duration: 60
  beamformer: RAW
  na: 1

RAW5PW:
  duration: 60
  beamformer: RAW
  na: 5

RAW11PW:
  duration: 60
  beamformer: RAW
  na: 11

ABLE1PW_auto:
  duration: 60
  beamformer: ABLE
  na: 1
  intensityAuto: True

ABLE5PW_auto:
  duration: 60
  beamformer: ABLE
  na: 5
  intensityAuto: True

ABLE11PW_auto:
  duration: 60
  beamformer: ABLE
  na: 11
  intensityAuto: True

reset_DAS1PW:
  duration: 1
  beamformer: DAS
  na: 1