"""Automatically generate comments in YAML config files based on parameter descriptions.

Run this script to add inline comments to all YAML config files under ``configs/``.
Also checks that PARAMETER_DESCRIPTIONS stays in sync with the ConfigSchema spec.
"""

import os
import re
import sys
from pathlib import Path

# Ensure the workspace version of zea is used when this script is run directly.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from zea import log
from zea.internal.config.parameters import PARAMETER_DESCRIPTIONS

AUTOGEN_HEADER_TEMPLATE = "# {filename} - comments were autogenerated from PARAMETER_DESCRIPTIONS in zea/config/parameters.py\n"
AUTOGEN_HEADER_KEYWORD = "autogenerated"


# Determine if we are running from the docs directory or project root
def get_project_paths():
    """Get the project paths for configs based on the current working directory."""
    cwd = Path.cwd().resolve()
    if cwd.name == "source" and cwd.parent.name == "docs":
        project_root = cwd.parent.parent
    elif cwd.name == "docs":
        project_root = cwd.parent
    else:
        project_root = cwd

    configs_dir = project_root / "configs"

    if not configs_dir.exists():
        raise FileNotFoundError(f"Configs directory does not exist: {configs_dir}")

    return configs_dir


CONFIGS_DIRNAME = get_project_paths()


def flatten_dict_keys(d, prefix=""):
    """Recursively flatten nested dict keys into dot notation, ignoring 'description' keys."""
    keys = set()
    for k, v in d.items():
        if k == "description":
            continue
        full = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            keys |= flatten_dict_keys(v, full)
        else:
            keys.add(full)
    return keys


def wrap_string_as_comment(input_string, indent_level=0, max_line_length=100, indent_size=2):
    """Limit the length of lines in a string and adds a comment prefix."""
    if isinstance(input_string, dict):
        input_string = input_string.get("description", "-")
    if not isinstance(input_string, str):
        input_string = str(input_string)
    indent = " " * (indent_level * indent_size)
    prefix = indent + "# "
    prefix_length = len(prefix)
    if max_line_length <= prefix_length:
        raise ValueError("max_line_length must be greater than the length of the prefix")
    words = input_string.split()
    result_lines = []
    current_line = prefix
    for word in words:
        if len(current_line) + len(word) + 1 > max_line_length:
            result_lines.append(current_line)
            current_line = prefix + word
        else:
            if current_line != prefix:
                current_line += " "
            current_line += word
    if current_line:
        result_lines.append(current_line)
    return "\n".join(result_lines) + "\n"


def process_yaml_content(lines, descriptions, indent_size=2):
    """Process YAML content line by line and add comments."""
    modified_lines = []
    current_keys = []
    for line in lines:
        if line.strip().startswith("#"):
            continue
        if re.match(r"^\s*\w+\s*:", line):
            indent_level = len(re.match(r"^\s*", line).group(0)) // indent_size
            current_keys = current_keys[:indent_level]
            key = line.split(":")[0].strip()
            current_keys.append(key)
            # Special handling: skip comments for operation entries inside pipeline.operations
            if (
                len(current_keys) >= 3
                and current_keys[0] == "pipeline"
                and current_keys[1] == "operations"
            ):
                modified_lines.append(line)
                continue
            description = descriptions
            try:
                for key in current_keys:
                    description = description[key]
            except Exception:
                description = "-"
            comment_lines = wrap_string_as_comment(
                description, indent_level, max_line_length=80, indent_size=indent_size
            )
            if comment_lines.strip() != "# -":
                modified_lines.append(comment_lines)
            modified_lines.append(line)
        else:
            modified_lines.append(line)
    return modified_lines


def add_comments_to_yaml(file_path, descriptions):
    """Adds comments to a YAML file based on a descriptions dictionary."""
    header = AUTOGEN_HEADER_TEMPLATE.format(filename=file_path.name)
    with open(file_path, "r", encoding="utf-8") as file:
        content = file.readlines()
    if content and content[0].startswith("#") and AUTOGEN_HEADER_KEYWORD in content[0]:
        content = content[1:]
    modified_content = process_yaml_content(content, descriptions)
    modified_content = [header] + modified_content
    with open(file_path, "w", encoding="utf-8") as file:
        file.writelines(modified_content)


def check_parameter_descriptions(descriptions, spec):
    """Check for missing or extra parameter descriptions (ignoring 'description' keys).

    ``spec`` is the top-level :class:`~zea.internal.config.validation.ConfigSpec`
    subclass. Returns (missing, extra) as sorted lists.
    """
    rst_keys = flatten_dict_keys(descriptions)
    schema_keys = spec.all_field_paths()
    missing = sorted(schema_keys - rst_keys)
    extra = sorted(rst_keys - schema_keys)
    return missing, extra


def update_configs(descriptions, configs_dir=CONFIGS_DIRNAME):
    """Update YAML config files with comments based on parameter descriptions."""
    config_dir = Path(configs_dir)
    yaml_files = [f for f in os.listdir(config_dir) if f.endswith(".yaml") or f.endswith(".yml")]
    for file_name in yaml_files:
        log.info(f"Adding comments to {config_dir / file_name}")
        add_comments_to_yaml(config_dir / file_name, descriptions)


if __name__ == "__main__":
    from zea.internal.config.validation import ConfigSchema

    # 1. Check parameter descriptions
    missing, extra = check_parameter_descriptions(PARAMETER_DESCRIPTIONS, ConfigSchema)
    if missing:
        log.warning(
            "The following config parameters are missing descriptions in PARAMETER_DESCRIPTIONS:"
        )
        for k in missing:
            print(f"- {k}")
    if extra:
        log.warning(
            "The following parameters are described in `zea.config.parameters.PARAMETER_DESCRIPTIONS` "
            "but do not exist in the config schema:"
        )
        for k in extra:
            print(f"- {k}")
    if missing or extra:
        log.error("Parameter description check failed. Please fix the above issues.")
        sys.exit(1)
    else:
        log.info("All config parameters are documented in PARAMETER_DESCRIPTIONS.")

    # 2. Update YAML configs with comments
    update_configs(PARAMETER_DESCRIPTIONS)
