"""Auto-generate the DataSpec RST section from spec.py source of truth.

Run from the project root::

    python docs/source/spec_doc.py

This writes ``docs/source/_spec_ref.rst``, which is included verbatim by
``data-acquisition.rst``.
"""

import sys
from dataclasses import MISSING, fields
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import numpy as np

from zea.data.spec import (
    AlignedData,
    Annotations,
    BeamformedData,
    ColorDopplerMap,
    DataSpec,
    EnvelopeData,
    Image,
    MetadataSpec,
    MetricsSpec,
    ProbePose,
    ProbeSpec,
    ScanSpec,
    Segmentation,
    ShearWaveElastographyMap,
    Signal1D,
    SosMap,
    StrainPercentageMap,
    Subject,
    TissueDopplerMap,
)

AUTOGEN_HEADER = """\
.. THIS FILE WAS AUTOGENERATED USING docs/source/spec_doc.py. DO NOT EDIT MANUALLY.
   Run ``python docs/source/spec_doc.py`` from the project root to regenerate.

"""

OUT_PATH = Path(__file__).parent / "_spec_ref.rst"

_IND = "   "  # 3-space RST indent unit

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _dtype_str(dtype) -> str:
    """Return inline-code RST for a dtype — always in double backticks."""
    if isinstance(dtype, tuple):
        return " | ".join(_dtype_str(d) for d in dtype)
    # Python str and numpy str_ both render as ``str``
    if dtype is str or dtype is np.str_:
        return "``str``"
    # Map numpy bool_ to bool for readability
    if dtype is np.bool_:
        return "``bool``"
    if hasattr(dtype, "__name__"):
        return f"``{dtype.__name__}``"
    return f"``{dtype}``"


def _shape_str(shape) -> str:
    if isinstance(shape, tuple) and shape and isinstance(shape[0], tuple):
        return " or ".join(_shape_str(s) for s in shape)
    if shape == ():
        return "scalar"
    return "(" + ", ".join(str(s) for s in shape) + ")"


def _is_optional(cls, name: str) -> bool:
    try:
        for f in fields(cls):
            if f.name == name:
                return f.default is not MISSING or f.default_factory is not MISSING
    except TypeError:
        pass
    return False


def _first_sentence(docstring: str) -> str:
    for line in (docstring or "").splitlines():
        line = line.strip()
        if line:
            return line
    return ""


BADGES = """\
.. |badge-req| replace:: :bdg-danger:`required`
.. |badge-opt| replace:: :bdg-secondary:`optional`
"""

# ---------------------------------------------------------------------------
# Table renderers
# ---------------------------------------------------------------------------


def rst_full_table(cls, base_indent: int = 0) -> str:
    """Render a spec class as a list-table with all columns including description."""
    schema = cls.SCHEMA
    meta = getattr(cls, "FIELD_METADATA", {})
    p = _IND * base_indent

    rows = []
    for fname, fspec in schema.items():
        fm = meta.get(fname, {})
        unit = fm.get("unit", "\u2013")
        desc = fm.get("description", "")

        if "spec" in fspec:
            sub = fspec["spec"]
            type_s = f":class:`~zea.data.spec.{sub.__name__}`"
            shape_s = "group"
        else:
            type_s = _dtype_str(fspec.get("dtype", ""))
            shape_s = _shape_str(fspec.get("shape", ()))

        opt = _is_optional(cls, fname)
        badge = "|badge-opt|" if opt else "|badge-req|"
        rows.append((fname, type_s, shape_s, unit, desc, badge))

    lines = [
        f"{p}.. list-table::",
        f"{p}   :header-rows: 1",
        f"{p}   :widths: 22 16 18 7 27 10",
        f"{p}",
        f"{p}   * - Field",
        f"{p}     - Type",
        f"{p}     - Shape",
        f"{p}     - Unit",
        f"{p}     - Description",
        f"{p}     - ",
    ]
    for fname, type_s, shape_s, unit, desc, badge in rows:
        lines += [
            f"{p}   * - ``{fname}``",
            f"{p}     - {type_s}",
            f"{p}     - {shape_s}",
            f"{p}     - {unit}",
            f"{p}     - {desc}",
            f"{p}     - {badge}",
        ]
    return "\n".join(lines)


def rst_compact_table(cls, base_indent: int = 0) -> str:
    """Render a spec class as a compact table without a description column."""
    schema = cls.SCHEMA
    meta = getattr(cls, "FIELD_METADATA", {})
    p = _IND * base_indent

    rows = []
    for fname, fspec in schema.items():
        fm = meta.get(fname, {})
        unit = fm.get("unit", "\u2013")

        if "spec" in fspec:
            sub = fspec["spec"]
            type_s = f":class:`~zea.data.spec.{sub.__name__}`"
            shape_s = "group"
        else:
            type_s = _dtype_str(fspec.get("dtype", ""))
            shape_s = _shape_str(fspec.get("shape", ()))

        opt = _is_optional(cls, fname)
        badge = "|badge-opt|" if opt else "|badge-req|"
        rows.append((fname, type_s, shape_s, unit, badge))

    lines = [
        f"{p}.. list-table::",
        f"{p}   :header-rows: 1",
        f"{p}   :widths: 22 20 28 10 10",
        f"{p}",
        f"{p}   * - Field",
        f"{p}     - Type",
        f"{p}     - Shape",
        f"{p}     - Unit",
        f"{p}     - ",
    ]
    for fname, type_s, shape_s, unit, badge in rows:
        lines += [
            f"{p}   * - ``{fname}``",
            f"{p}     - {type_s}",
            f"{p}     - {shape_s}",
            f"{p}     - {unit}",
            f"{p}     - {badge}",
        ]
    return "\n".join(lines)


def rst_dropdown(cls, title, base_indent=0, open_=False, compact=False) -> str:
    """Render a spec class as a sphinx-design dropdown."""
    p = _IND * base_indent
    pi = _IND * (base_indent + 1)

    parts = [f"{p}.. dropdown:: {title}"]
    if open_:
        parts.append(f"{p}   :open:")
    parts.append("")

    doc_line = _first_sentence(cls.__doc__)
    if doc_line:
        parts.append(f"{pi}{doc_line}")
        parts.append("")

    table_fn = rst_compact_table if compact else rst_full_table
    parts.append(table_fn(cls, base_indent=base_indent + 1))
    parts.append("")

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Static RST blocks
# ---------------------------------------------------------------------------

FILE_TREE = """\
.. code-block:: text

   data_file.hdf5         (attrs: us_machine, description, zea_version)
   \u251c\u2500\u2500 data/
   \u2502   \u251c\u2500\u2500 raw_data                  float32 | int16  (n_frames, n_tx, n_ax, n_el, n_ch)
   \u2502   \u251c\u2500\u2500 aligned_data/             group (AlignedData)
   \u2502   \u251c\u2500\u2500 beamformed_data/          group (BeamformedData)
   \u2502   \u251c\u2500\u2500 envelope_data/            group (EnvelopeData)
   \u2502   \u251c\u2500\u2500 image/                    group (Image)
   \u2502   \u251c\u2500\u2500 segmentation/             group (Segmentation)
   \u2502   \u251c\u2500\u2500 sos_map/                  group (SosMap)
   \u2502   \u251c\u2500\u2500 strain_percentage_map/    group (StrainPercentageMap)
   \u2502   \u251c\u2500\u2500 tissue_doppler/           group (TissueDopplerMap)
   \u2502   \u251c\u2500\u2500 color_doppler/            group (ColorDopplerMap)
   \u2502   \u2514\u2500\u2500 <custom>/                 group (any spatial map)
   \u251c\u2500\u2500 scan/
   \u2502   \u251c\u2500\u2500 sampling_frequency        float32  scalar
   \u2502   \u251c\u2500\u2500 center_frequency          float32  scalar | (n_tx,)
   \u2502   \u251c\u2500\u2500 t0_delays                 float32  (n_tx, n_el)
   \u2502   \u2514\u2500\u2500 \u2026
   \u251c\u2500\u2500 metadata/
   \u2502   \u251c\u2500\u2500 subject/                  group (Subject)
   \u2502   \u251c\u2500\u2500 annotations/              group (Annotations)
   \u2502   \u251c\u2500\u2500 ecg/                      group (Signal1D)
   \u2502   \u2514\u2500\u2500 \u2026
   \u2514\u2500\u2500 metrics/
       \u2514\u2500\u2500 \u2026
"""  # noqa: E501

ROOT_ATTRS_TABLE = """\
.. list-table::
   :header-rows: 1
   :widths: 22 10 28 30 10

   * - Attribute
     - Type
     - Description
     - Values
     -
   * - ``us_machine``
     - ``str``
     - Name of the ultrasound system.
     - e.g. ``"Verasonics Vantage 256"``
     - |badge-opt|
   * - ``description``
     - ``str``
     - Free-text description of the acquisition.
     -
     - |badge-opt|
   * - ``zea_version``
     - ``str``
     - Version of zea that wrote this file (set automatically).
     -
     - |badge-opt|
"""

# Short descriptions for each grouped data type
MAP_DESCRIPTIONS = {
    "aligned_data": "Time-of-flight corrected data. Values are ``float32`` or ``int16`` in (n_frames, n_tx, n_ax, n_el, n_ch); ``labels`` names each channel (RF or I/Q).",  # noqa: E501
    "beamformed_data": "Beamformed (beamsummed) data. Values are ``float32`` in (n_frames, z, x, n_ch) or (n_frames, z, x, y, n_ch); ``labels`` names each channel (RF or I/Q).",  # noqa: E501
    "envelope_data": "Envelope-detected data. Values are ``float32`` in (n_frames, z, x) or (n_frames, z, x, y).",  # noqa: E501
    "image": "Reconstructed (log-compressed) image. Values are ``uint8`` in (n_frames, z, x) or (n_frames, z, x, y).",  # noqa: E501
    "segmentation": "Semantic segmentation mask. Values are ``bool`` in (n_frames, z, x, y, n_labels); ``labels`` names each channel.",  # noqa: E501
    "sos_map": "Speed-of-sound map in m/s. Values are ``float32``.",
    "strain_percentage_map": "Strain map in %. Values are ``float32``.",
    "shear_wave_elastography_map": "Shear-wave elastography map in m/s. Values are ``float32``.",
    "tissue_doppler": "Tissue Doppler velocity map in m/s. Values are ``float32``.",
    "color_doppler": "Color Doppler velocity map in m/s. Positive = towards probe. Values are ``float32``.",  # noqa: E501
}


# ---------------------------------------------------------------------------
# generate
# ---------------------------------------------------------------------------


def generate() -> str:
    lines = [AUTOGEN_HEADER, BADGES, ""]

    # --- File hierarchy -------------------------------------------------------
    lines += [
        "File hierarchy",
        "--------------",
        "",
        "Every ``zea`` HDF5 file follows the layout shown below.",
        "",
        FILE_TREE,
        "",
    ]

    # --- Root attributes ------------------------------------------------------
    lines += [
        "Root attributes",
        "~~~~~~~~~~~~~~~",
        "",
        "Stored as HDF5 root-level attributes (not groups).",
        "",
        ROOT_ATTRS_TABLE,
        "",
    ]

    # --- Group reference tabs -------------------------------------------------
    lines += [
        "Group reference",
        "~~~~~~~~~~~~~~~",
        "",
        "Click a group tab to explore its fields.",
        "Fields marked :bdg-secondary:`optional` may be absent; all others are",
        ":bdg-danger:`required`.",
        "",
        ".. tab-set::",
        "",
    ]

    # ---- data tab ------------------------------------------------------------
    lines += [
        "   .. tab-item:: data",
        "      :sync: data",
        "",
        "      Data group containing raw channel data, derived pipeline products,",
        "      and optional grouped data products.",
        "",
        "      **Data fields**",
        "",
        rst_full_table(DataSpec, base_indent=2),
        "",
        "      **Grouped data products**",
        "",
        "      Each grouped data product is an HDF5 sub-group. Spatial map groups",
        "      (beamformed_data, envelope_data, image, segmentation, and custom maps)",
        "      also include a ``coordinates`` field (per-pixel Cartesian positions in",
        "      metres, shape ``(*spatial_dims, 3)`` where ``spatial_dims`` matches the spatial",
        "      (non-channel) dimensions of ``values``).",
        "      Custom spatial maps are also accepted — any extra key passed to",
        "      :class:`~zea.data.spec.DataSpec` is validated as a generic",
        "      :class:`~zea.data.spec.Map` sub-group.",
        "",
    ]

    map_classes = [
        ("aligned_data", AlignedData),
        ("beamformed_data", BeamformedData),
        ("envelope_data", EnvelopeData),
        ("image", Image),
        ("segmentation", Segmentation),
        ("sos_map", SosMap),
        ("strain_percentage_map", StrainPercentageMap),
        ("shear_wave_elastography_map", ShearWaveElastographyMap),
        ("tissue_doppler", TissueDopplerMap),
        ("color_doppler", ColorDopplerMap),
    ]

    for fname, cls in map_classes:
        desc = MAP_DESCRIPTIONS.get(fname, _first_sentence(cls.__doc__))
        p2 = _IND * 2
        p3 = _IND * 3
        lines += [
            f"{p2}.. dropdown:: ``{fname}``",
            "",
            f"{p3}{desc}",
            "",
            rst_compact_table(cls, base_indent=3),
            "",
        ]

    # ---- scan tab ------------------------------------------------------------
    lines += [
        "   .. tab-item:: scan",
        "      :sync: scan",
        "",
        "      Scan group with acquisition and transmit sequence parameters.",
        "",
        rst_full_table(ScanSpec, base_indent=2),
        "",
    ]
    # ---- probe tab -----------------------------------------------------------
    lines += [
        "   .. tab-item:: probe",
        "      :sync: probe",
        "",
        "      Probe group with probe geometry and frequency parameters.",
        "",
        rst_full_table(ProbeSpec, base_indent=2),
        "",
    ]
    # ---- metadata tab --------------------------------------------------------
    lines += [
        "   .. tab-item:: metadata",
        "      :sync: metadata",
        "",
        "      Optional metadata group for subject, acquisition context, annotations,",
        "      and extra time-series signals (ECG, voice narration, probe orientation).",
        "      Extra signal keys are accepted and validated as",
        "      :class:`~zea.data.spec.SignalND` sub-groups.",
        "",
        rst_full_table(MetadataSpec, base_indent=2),
        "",
        "      **Sub-groups**",
        "",
    ]
    meta_subs = [
        ("subject", Subject, True),
        ("annotations", Annotations, True),
        ("probe_pose", ProbePose, False),
        ("ecg / voice_narration", Signal1D, False),
    ]
    for label, cls, compact in meta_subs:
        lines += [
            rst_dropdown(
                cls,
                f"``{label}`` \u2014 {cls.__name__}",
                base_indent=2,
                compact=compact,
            ),
            "",
        ]

    # ---- metrics tab ---------------------------------------------------------
    lines += [
        "   .. tab-item:: metrics",
        "      :sync: metrics",
        "",
        "      Optional metrics group for acquisition-level quality and performance metrics.",
        "",
        rst_full_table(MetricsSpec, base_indent=2),
        "",
    ]

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    content = generate()
    OUT_PATH.write_text(content)
    print(f"Written: {OUT_PATH}")
