probes:
  S5_1:
    num_elements: 80
    element_width_mm: 0.25
    element_spacing_mm: 0.254
  ViewFlex:
    num_elements: 64
    element_width_mm: 0.2
    element_spacing_mm: 0.205
  L15_7io:
    num_elements: 128
    element_width_mm: 0.0902
    element_spacing_mm: 0.0902
