model:
  beamformer:
    type: nmap
    folds: 4
    end_with_prox: true
    proxtype: wavelet
    kernel_size: 1
  patch_shape: [128, 128]
  batch_size: 1

scan:
  xlims: [-0.019, 0.019]
  zlims: [0, 0.063]
  Nx: null # If set to "null", a square pixel grid of lambda/3 is generated (TODO)
  Nz: null

data:
  local: false
  dataset: 'ben/US_Data/'
  input_type: 'input'
  target_type: 'output_1pw_mv_preenvelope'
  env_detect_pred: false
  env_detect_target: true
  file_path: null
  dataset_name: 'abledata'
  dtype: 'raw_data'
  modtype: 'rf'
  dynamic_range: [-60, 0]
  n_angles: 1
  input_noise: 0
  probe_type: L11-4v
  angles: [5]
  IQ: true

device: 'gpu'

plot:
  save: true