model:
  beamformer:
    type: nmap
    folds: 4
    end_with_prox: true
    proxtype: wavelet
    kernel_size: 1
  patch_shape: [128, 128]
  batch_size: 1

scan:
  xlims: [-0.019, 0.019]
  zlims: [0, 0.063]
  Nx: null # If set to "null", a square pixel grid of lambda/3 is generated (TODO)
  Nz: null
  n_angles: 11

data:
  file_path: null
  local: true
  dataset_name: 'abledata'
  dtype: 'raw_data'
  modtype: 'rf'
  dynamic_range: [-60, 0]

scan:
  n_angles: 75

device: 'gpu'
ml_library: 'tensorflow'

plot:
  save: true
  axis: true
