name: Pytest

on:
  pull_request:
  push:
    branches:
    - main
    - develop

# Source: https://github.com/marketplace/actions/install-poetry-action
jobs:
  run_tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.8.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install project
        run: poetry install --no-interaction --no-root --with torch,tensorflow,jax -E opencv-python-headless

      - name: Perform tests
        run: poetry run pytest -s ./tests
